server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://tramway.proxy.rlwy.net:36614/railway
    username: postgres
    password: xsJOJkIJVfxhmvdndKgjTTqvGtpZtrXM
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  # mail:
  #   host: smtp.gmail.com
  #   port: 587
  #   username: yogazikrisaputra@gmail.com
  #   password: nacv wwxr hfeb hqld
  #   protocol: smtp
  #   properties:
  #     mail:
  #       smtp:
  #         auth: true
  #         starttls:
  #           enable: true

  application:
  attachment:
    upload-dir: ./data/attachments

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
  cache:
    disabled: true
